"""add scene_id to voiceovers

Revision ID: 018aee52f3e6
Revises: 4ac07de4567b
Create Date: 2026-09-06 18:00:43.039479

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '018aee52f3e6'
down_revision: str | None = '4ac07de4567b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voiceovers', sa.Column('scene_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'voiceovers', 'scenes', ['scene_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'voiceovers', type_='foreignkey')
    op.drop_column('voiceovers', 'scene_id')
    # ### end Alembic commands ###
