"""add source videos and clips

Revision ID: 3965f368e0ab
Revises: f0f0e2eaa26c
Create Date: 2026-10-03 14:42:46.567372

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '3965f368e0ab'
down_revision: str | None = 'f0f0e2eaa26c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_videos',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('source_path', sa.String(length=1000), nullable=False),
    sa.Column('stage', sa.Enum('UPLOADED', 'TRANSCRIBING', 'SELECTING_CLIPS', 'EXTRACTING', 'COMPLETED', 'FAILED', name='clip_job_stage'), nullable=False),
    sa.Column('stage_detail', sa.Text(), nullable=False),
    sa.Column('target_clip_count', sa.Integer(), nullable=False),
    sa.Column('transcript_path', sa.String(length=1000), nullable=True),
    sa.Column('auto_publish', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clips',
    sa.Column('source_video_id', sa.UUID(), nullable=False),
    sa.Column('start_seconds', sa.Float(), nullable=False),
    sa.Column('end_seconds', sa.Float(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('clip_path', sa.String(length=1000), nullable=True),
    sa.Column('youtube_video_id', sa.String(length=50), nullable=True),
    sa.Column('youtube_published', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_video_id'], ['source_videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clips')
    op.drop_table('source_videos')
    # ### end Alembic commands ###
