"""add music_track to videos

Revision ID: 4a55006f7f54
Revises: e826a60138d4
Create Date: 2026-09-06 22:48:04.016351

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '4a55006f7f54'
down_revision: str | None = 'e826a60138d4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('music_track', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'music_track')
    # ### end Alembic commands ###
