"""add cost_entries table

Revision ID: 4ac07de4567b
Revises: d1050c39cff2
Create Date: 2026-09-06 15:50:08.480398

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '4ac07de4567b'
down_revision: str | None = 'd1050c39cff2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_entries',
    sa.Column('category', sa.Enum('GPU', 'LLM', 'TTS', 'VIDEO_GENERATION', 'STORAGE', 'DATABASE', 'HOSTING', 'NETWORKING', 'DOMAIN', 'OTHER', name='cost_category'), nullable=False),
    sa.Column('service', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=True),
    sa.Column('actual_cost_usd', sa.Float(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cost_entries')
    # ### end Alembic commands ###
