"""add upload schedules

Revision ID: d590753a94ee
Revises: 56dbf9e8cdc8
Create Date: 2026-10-03 08:44:02.448771

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'd590753a94ee'
down_revision: str | None = '56dbf9e8cdc8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_schedules',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('trigger_time', sa.String(length=5), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('target_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('voice_preset', sa.String(length=100), nullable=False),
    sa.Column('style_preset', sa.String(length=100), nullable=False),
    sa.Column('run_research', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_triggered_on', sa.String(length=10), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upload_schedules')
    # ### end Alembic commands ###
