"""add auth, signup pins, and compliance reports

Revision ID: e826a60138d4
Revises: 018aee52f3e6
Create Date: 2026-09-06 22:20:43.290863

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e826a60138d4'
down_revision: str | None = '018aee52f3e6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('signup_pins',
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('used_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['used_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_hash')
    )
    op.create_table('compliance_reports',
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('blockers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # The existing users table may already have rows (there's exactly one —
    # Nobert) with no password_hash/role to backfill from, so this column
    # set is added with a one-time server_default (removed right after)
    # rather than left nullable.
    user_role = postgresql.ENUM('ADMIN', 'USER', name='user_role')
    user_role.create(op.get_bind())
    op.add_column(
        'users',
        sa.Column('password_hash', sa.String(length=255), nullable=False, server_default=''),
    )
    op.add_column(
        'users',
        sa.Column('role', user_role, nullable=False, server_default='USER'),
    )
    op.add_column(
        'users', sa.Column('is_suspended', sa.Boolean(), nullable=False, server_default='false')
    )
    op.add_column(
        'users', sa.Column('token_balance', sa.Integer(), nullable=False, server_default='0')
    )
    op.alter_column('users', 'password_hash', server_default=None)
    op.alter_column('users', 'role', server_default=None)
    op.alter_column('users', 'is_suspended', server_default=None)
    op.alter_column('users', 'token_balance', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_balance')
    op.drop_column('users', 'is_suspended')
    op.drop_column('users', 'role')
    op.drop_column('users', 'password_hash')
    op.drop_table('compliance_reports')
    op.drop_table('signup_pins')
    op.drop_table('auth_sessions')
    postgresql.ENUM(name='user_role').drop(op.get_bind())
    # ### end Alembic commands ###
