"""add auto publish and video feedback

Revision ID: eb99ad62e1a7
Revises: d590753a94ee
Create Date: 2026-10-03 09:11:11.121608

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'eb99ad62e1a7'
down_revision: str | None = 'd590753a94ee'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_feedback',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('upload_schedules', sa.Column('auto_publish', sa.Boolean(), nullable=False))
    op.add_column('videos', sa.Column('auto_publish', sa.Boolean(), nullable=False))
    op.add_column('videos', sa.Column('youtube_video_id', sa.String(length=50), nullable=True))
    op.add_column('videos', sa.Column('youtube_published', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'youtube_published')
    op.drop_column('videos', 'youtube_video_id')
    op.drop_column('videos', 'auto_publish')
    op.drop_column('upload_schedules', 'auto_publish')
    op.drop_table('video_feedback')
    # ### end Alembic commands ###
